import { defineComponent } from 'vue'
import { flushPromises, mount, type VueWrapper } from '@vue/test-utils'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import UpstreamStorageDialog from './UpstreamStorageDialog.vue'
import Select from '@/components/common/Select.vue'
import type { UpstreamStoragePolicy } from '@/api/admin/upstreamCenter'
const api = vi.hoisted(() => ({ storage: vi.fn(), updateStorage: vi.fn(), cleanupStorage: vi.fn(), archives: vi.fn(), purge: vi.fn() }))
vi.mock('@/api/admin/upstreamCenter', () => ({ upstreamCenterAPI: api }))
vi.mock('vue-i18n', () => ({ useI18n: () => ({ t: (key: string) => key }) }))
const dialog = defineComponent({ props: ['show'], template: '<div v-if="show"><slot /><slot name="footer" /></div>' })
const policy = (): UpstreamStoragePolicy => ({ enabled: true, history_retention_days: 30, snapshot_retention_days: 7, last_cleanup_at: null, last_result: null })
let view: VueWrapper | undefined
function render(realDialog = false) { view = mount(UpstreamStorageDialog, { attachTo: realDialog ? document.body : undefined, props: { show: true }, global: { stubs: { BaseDialog: realDialog ? false : dialog, Icon: true, teleport: true, transition: true } } }); return view }
beforeEach(() => { vi.clearAllMocks(); api.storage.mockResolvedValue(policy()); api.archives.mockResolvedValue({ items: [], total: 0 }); api.updateStorage.mockImplementation(async input => ({ ...policy(), ...input })); api.purge.mockResolvedValue(undefined) })
afterEach(() => { view?.unmount(); view = undefined; document.body.innerHTML = ''; document.body.classList.remove('modal-open') })
describe('upstream storage controls', () => {
  it('loads the saved policy, uses native pickers without search, and requires saving before cleanup', async () => {
    const wrapper = render(); await flushPromises()
    const selects = wrapper.findAllComponents(Select)
    expect(selects).toHaveLength(2)
    expect(selects.every(select => select.props('searchable') === false)).toBe(true)
    expect(selects[0]!.props('modelValue')).toBe(30)
    expect(selects[1]!.props('modelValue')).toBe(7)
    expect(selects[0]!.props('options').map((item: { value: number }) => item.value)).toEqual([30, 60, 90, 180, 365])
    expect(selects[1]!.props('options').map((item: { value: number }) => item.value)).toEqual([1, 3, 7, 30, 90])
    selects[0]!.vm.$emit('update:modelValue', 90)
    await wrapper.get('#storage-enabled').trigger('click')
    expect(wrapper.get('[data-testid="cleanup-storage"]').attributes('disabled')).toBeDefined()
    expect(api.cleanupStorage).not.toHaveBeenCalled()
    await wrapper.get('[data-testid="save-storage"]').trigger('click'); await flushPromises()
    expect(api.updateStorage).toHaveBeenCalledWith({ enabled: false, history_retention_days: 90, snapshot_retention_days: 7 })
    expect(wrapper.get('[data-testid="cleanup-storage"]').attributes('disabled')).toBeUndefined()
  })
  it('runs only one bounded cleanup per click and shows its counts and continuation hint', async () => {
    const result = { history_deleted: 3000, balance_deleted: 12, billing_deleted: 8, has_more: true }
    api.cleanupStorage.mockResolvedValue(result)
    api.storage.mockResolvedValueOnce(policy()).mockResolvedValue({ ...policy(), last_cleanup_at: '2026-09-26T00:00:00Z', last_result: result })
    const wrapper = render(); await flushPromises()
    await wrapper.get('[data-testid="cleanup-storage"]').trigger('click'); await flushPromises()
    expect(api.cleanupStorage).toHaveBeenCalledTimes(1)
    expect(wrapper.text()).toContain('3,000')
    expect(wrapper.get('[data-testid="cleanup-has-more"]').text()).toBe('upstreamCenter.storage.hasMore')
    expect(wrapper.get('[data-testid="cleanup-storage"]').text()).toContain('upstreamCenter.storage.continueCleanup')
    expect(wrapper.emitted('changed')).toHaveLength(1)
  })
  it('shows OAuth archives and requires name confirmation before deleting, keeping busy errors visible', async () => {
    const item = { kind: 'intelligence', id: 7, name: 'OAuth account', source_type: 'openai_oauth', supplier_name: '', deleted_at: '2026-09-26T00:00:00Z' }
    api.archives.mockResolvedValue({ items: [item], total: 201 })
    api.purge.mockRejectedValueOnce({ status: 409, message: 'This plan is running.' }).mockResolvedValue(undefined)
    const wrapper = render(); await flushPromises()
    expect(wrapper.text()).toContain('upstreamCenter.storage.kinds.oauth')
    expect(wrapper.text()).toContain('upstreamCenter.storage.archiveLimit')
    await wrapper.get('[data-archive="intelligence-7"] button').trigger('click')
    expect(wrapper.get('[data-testid="confirm-removal"]').attributes('disabled')).toBeDefined()
    await wrapper.get('[data-testid="purge-confirm-name"]').setValue('OAuth account')
    await wrapper.get('[data-testid="confirm-removal"]').trigger('click'); await flushPromises()
    expect(api.purge).toHaveBeenCalledWith({ kind: 'intelligence', id: 7, confirm_name: 'OAuth account' })
    expect(wrapper.text()).toContain('This plan is running.')
    expect(wrapper.find('[data-testid="purge-confirm-name"]').exists()).toBe(true)
    api.archives.mockResolvedValue({ items: [], total: 0 })
    await wrapper.get('[data-testid="confirm-removal"]').trigger('click'); await flushPromises()
    expect(wrapper.find('[data-testid="purge-confirm-name"]').exists()).toBe(false)
    expect(wrapper.find('[data-archive]').exists()).toBe(false)
    expect(wrapper.emitted('changed')).toHaveLength(1)
  })
  it('ignores a late policy response after closing and reopening', async () => {
    let oldResponse: (value: UpstreamStoragePolicy) => void = () => undefined
    api.storage.mockReturnValueOnce(new Promise(resolve => { oldResponse = resolve })).mockResolvedValueOnce({ ...policy(), history_retention_days: 180 })
    const wrapper = render()
    await wrapper.setProps({ show: false }); await wrapper.setProps({ show: true }); await flushPromises()
    oldResponse({ ...policy(), history_retention_days: 365 }); await flushPromises()
    expect(wrapper.findAllComponents(Select)[0]!.props('modelValue')).toBe(180)
  })
  it('closes only the nested confirmation on Escape and preserves the parent scroll lock', async () => {
    const item = { kind: 'target', id: 7, name: 'Archived monitor', source_type: '', supplier_name: '', deleted_at: '2026-09-26T00:00:00Z' }
    api.archives.mockResolvedValue({ items: [item], total: 1 })
    const wrapper = render(true); await flushPromises()
    await wrapper.get('[data-archive="target-7"] button').trigger('click'); await flushPromises()
    expect(wrapper.findAll('[role="dialog"]')).toHaveLength(2)
    document.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape', bubbles: true }))
    await flushPromises()
    expect(wrapper.findAll('[role="dialog"]')).toHaveLength(1)
    expect(wrapper.emitted('close')).toBeUndefined()
    expect(document.body.classList.contains('modal-open')).toBe(true)
    expect(api.purge).not.toHaveBeenCalled()
  })
  it('clears old archives during a new session and ignores the old request after reopening', async () => {
    const item = { kind: 'target', id: 7, name: 'Old monitor', source_type: '', supplier_name: '', deleted_at: '2026-09-26T00:00:00Z' }
    api.archives.mockResolvedValueOnce({ items: [item], total: 1 })
    const wrapper = render(); await flushPromises()
    expect(wrapper.find('[data-archive="target-7"]').exists()).toBe(true)
    let finishOld: (value: unknown) => void = () => undefined
    api.archives.mockReturnValueOnce(new Promise(resolve => { finishOld = resolve }))
    await wrapper.setProps({ show: false }); await wrapper.setProps({ show: true }); await flushPromises()
    expect(wrapper.find('[data-archive]').exists()).toBe(false)
    api.archives.mockResolvedValueOnce({ items: [], total: 0 })
    await wrapper.setProps({ show: false }); await wrapper.setProps({ show: true }); await flushPromises()
    finishOld({ items: [item], total: 1 }); await flushPromises()
    expect(wrapper.find('[data-archive]').exists()).toBe(false)
    expect(wrapper.text()).toContain('upstreamCenter.storage.emptyArchives')
  })
  it('keeps a completed purge removed even when the archive refresh fails', async () => {
    const item = { kind: 'target', id: 7, name: 'Gone monitor', source_type: '', supplier_name: '', deleted_at: '2026-09-26T00:00:00Z' }
    api.archives.mockResolvedValueOnce({ items: [item], total: 1 }).mockRejectedValueOnce({ message: 'Archive refresh failed' })
    const wrapper = render(); await flushPromises()
    await wrapper.get('[data-archive="target-7"] button').trigger('click')
    await wrapper.get('[data-testid="purge-confirm-name"]').setValue(item.name)
    await wrapper.get('[data-testid="confirm-removal"]').trigger('click'); await flushPromises()
    expect(wrapper.find('[data-archive="target-7"]').exists()).toBe(false)
    expect(wrapper.text()).toContain('Archive refresh failed')
    expect(wrapper.text()).toContain('upstreamCenter.storage.purged')
    expect(wrapper.text()).not.toContain('upstreamCenter.storage.emptyArchives')
  })
  it('distinguishes successful cleanup from a failed status refresh and does not run a second cleanup', async () => {
    const result = { history_deleted: 27, balance_deleted: 5, billing_deleted: 3, has_more: false }
    api.cleanupStorage.mockResolvedValue(result)
    api.storage.mockResolvedValueOnce(policy()).mockRejectedValueOnce({ message: 'Refresh failed' })
    const wrapper = render(); await flushPromises()
    await wrapper.get('[data-testid="cleanup-storage"]').trigger('click'); await flushPromises()
    expect(api.cleanupStorage).toHaveBeenCalledTimes(1)
    expect(wrapper.text()).toContain('upstreamCenter.storage.cleaned')
    expect(wrapper.text()).toContain('upstreamCenter.storage.refreshAfterCleanupFailed')
    expect(wrapper.text()).not.toContain('upstreamCenter.storage.actionFailed')
    expect(wrapper.text()).toContain('27')
  })
  it('prevents closing or duplicate requests while saving and keeps draft values after failure', async () => {
    let rejectSave: (value: unknown) => void = () => undefined
    api.updateStorage.mockReturnValueOnce(new Promise((_, reject) => { rejectSave = reject }))
    const wrapper = render(); await flushPromises()
    wrapper.findAllComponents(Select)[0]!.vm.$emit('update:modelValue', 90)
    await flushPromises()
    await wrapper.get('[data-testid="save-storage"]').trigger('click')
    await wrapper.get('[data-testid="save-storage"]').trigger('click')
    wrapper.getComponent(dialog).vm.$emit('close'); await flushPromises()
    expect(wrapper.emitted('close')).toBeUndefined()
    expect(api.updateStorage).toHaveBeenCalledTimes(1)
    expect(wrapper.get('#storage-enabled').attributes('disabled')).toBeDefined()
    expect(wrapper.get('[data-testid="cleanup-storage"]').attributes('disabled')).toBeDefined()
    rejectSave({ message: 'Save failed' }); await flushPromises()
    expect(wrapper.findAllComponents(Select)[0]!.props('modelValue')).toBe(90)
    expect(wrapper.get('[data-testid="save-storage"]').attributes('disabled')).toBeUndefined()
    expect(wrapper.text()).toContain('Save failed')
  })
})
