import { defineComponent } from 'vue'
import { flushPromises, mount, type VueWrapper } from '@vue/test-utils'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import UpstreamSupplierDialog from './UpstreamSupplierDialog.vue'

const mocks = vi.hoisted(() => ({ createSupplier: vi.fn(), updateSupplier: vi.fn(), createTarget: vi.fn(), overview: vi.fn(), list: vi.fn(), getById: vi.fn() }))
vi.mock('@/api/admin/upstreamCenter', () => ({ upstreamCenterAPI: { createSupplier: mocks.createSupplier, updateSupplier: mocks.updateSupplier, createTarget: mocks.createTarget, overview: mocks.overview } }))
vi.mock('@/api/admin/accounts', () => ({ list: mocks.list, getById: mocks.getById }))
vi.mock('vue-i18n', () => ({ useI18n: () => ({ t: (key: string) => key }) }))
const dialog = defineComponent({ props: ['show'], template: '<div v-if="show"><slot /><slot name="footer" /></div>' })
let wrapper: VueWrapper | undefined
function render() { wrapper = mount(UpstreamSupplierDialog, { props: { show: true, supplier: null }, global: { stubs: { BaseDialog: dialog, Icon: true } } }); return wrapper }
const account = (id: number) => ({ id, name: `Account ${id}`, platform: 'openai', credentials: { base_url: 'https://upstream.example/v1', ...(id === 1 ? { model_mapping: { 'model-from-account': 'remote-model' } } : {}) } })
const supplier = { id: 10, name: 'Account 1', website: 'https://upstream.example', targets: [] }
beforeEach(() => {
  vi.resetAllMocks()
  mocks.list.mockResolvedValue({ items: [account(1), account(2)], total: 2 })
  mocks.getById.mockImplementation(async (id: number) => account(id))
  mocks.createSupplier.mockResolvedValue(supplier)
  mocks.createTarget.mockResolvedValue({ id: 30 })
  mocks.overview.mockResolvedValue({ suppliers: [supplier], monitors: [] })
})
afterEach(() => wrapper?.unmount())
async function choose(view: VueWrapper, id: number) { await view.get(`input[aria-label="Account ${id}"]`).setValue(true); await flushPromises() }

describe('upstream account batch import', () => {
  it('isolates pending account imports when the supplier form closes and reopens', async () => {
    let rejectOldImport: (error: unknown) => void = () => undefined
    let resolveNewImport: (value: unknown) => void = () => undefined
    mocks.getById.mockReturnValueOnce(new Promise((_, reject) => { rejectOldImport = reject }))
      .mockReturnValueOnce(new Promise(resolve => { resolveNewImport = resolve }))
    const view = render()
    await flushPromises()
    await view.get('input[aria-label="Account 1"]').setValue(true)
    await view.setProps({ show: false })
    await view.setProps({ show: true })
    await flushPromises()
    const checkbox = () => view.get('input[aria-label="Account 1"]')
    expect(checkbox().attributes('disabled')).toBeUndefined()
    await checkbox().setValue(true)
    expect(mocks.getById).toHaveBeenCalledTimes(2)

    rejectOldImport({ message: 'Old supplier import failed' })
    await flushPromises()
    expect(view.text()).not.toContain('Old supplier import failed')
    expect(checkbox().attributes('disabled')).toBeDefined()

    resolveNewImport(account(1))
    await flushPromises()
    expect(view.find('#import-model-1').exists()).toBe(true)
    expect(checkbox().attributes('disabled')).toBeUndefined()
  })
  it('creates key groups with shared defaults despite account model mapping and accepts custom settings', async () => {
    const view = render(); await flushPromises()
    await choose(view, 1); await choose(view, 2)
    expect((view.get('#supplier-website').element as HTMLInputElement).value).toBe('https://upstream.example')
    expect((view.get('#import-model-1').element as HTMLInputElement).value).toBe('gpt-5.6-sol')
    expect((view.get('#import-model-2').element as HTMLInputElement).value).toBe('gpt-5.6-sol')
    expect((view.get('#import-interval-1').element as HTMLInputElement).value).toBe('30')
    expect(view.get('#import-interval-1').attributes('min')).toBe('30')
    await view.get('#import-model-2').setValue('model-a, model-b')
    await view.get('#import-interval-2').setValue('90')
    await view.get('form').trigger('submit'); await flushPromises()
    expect(mocks.createSupplier).toHaveBeenCalledTimes(1)
    expect(mocks.createTarget).toHaveBeenCalledTimes(2)
    expect(mocks.createTarget).toHaveBeenNthCalledWith(1, expect.objectContaining({ supplier_id: 10, account_ids: [1], endpoint: 'https://upstream.example/v1', models: ['gpt-5.6-sol'], interval_seconds: 30, enabled: true }))
    expect(mocks.createTarget).toHaveBeenNthCalledWith(2, expect.objectContaining({ supplier_id: 10, account_ids: [2], models: ['model-a', 'model-b'], interval_seconds: 90 }))
    expect(mocks.createTarget.mock.calls.every(([input]) => !('api_key' in input))).toBe(true)
    expect(view.emitted('saved')).toHaveLength(1)
  })
  it.each(['anthropic', 'gemini'])('uses the same editable monitoring defaults for %s imports', async platform => {
    mocks.getById.mockResolvedValue({ ...account(1), platform })
    const view = render()
    await flushPromises()
    await choose(view, 1)
    expect((view.get('#import-model-1').element as HTMLInputElement).value).toBe('gpt-5.6-sol')
    await view.get('form').trigger('submit')
    await flushPromises()
    expect(mocks.createTarget).toHaveBeenCalledWith(expect.objectContaining({ provider: platform, models: ['gpt-5.6-sol'], interval_seconds: 30 }))
  })
  it('retries only failed groups without recreating the supplier or successful groups', async () => {
    mocks.createTarget.mockResolvedValueOnce({ id: 30 }).mockRejectedValueOnce({ message: 'Account is already bound.' }).mockResolvedValueOnce({ id: 31 })
    const view = render(); await flushPromises(); await choose(view, 1); await choose(view, 2)
    await view.get('form').trigger('submit'); await flushPromises()
    expect(view.text()).toContain('Account is already bound.')
    expect(view.emitted('close')).toBeUndefined()
    expect(view.emitted('saved')).toBeUndefined()
    await view.get('form').trigger('submit'); await flushPromises()
    expect(mocks.createSupplier).toHaveBeenCalledTimes(1)
    expect(mocks.createTarget).toHaveBeenCalledTimes(3)
    expect(mocks.createTarget.mock.calls.map(([input]) => input.account_ids)).toEqual([[1], [2], [2]])
    expect(view.emitted('saved')).toHaveLength(1)
  })
  it('recovers a lost supplier response without creating a duplicate', async () => {
    mocks.createSupplier.mockRejectedValueOnce({ message: 'Network error after save' })
    const view = render(); await flushPromises(); await choose(view, 1)
    await view.get('form').trigger('submit'); await flushPromises()
    expect(view.text()).toContain('Network error after save')
    await view.get('form').trigger('submit'); await flushPromises()
    expect(mocks.createSupplier).toHaveBeenCalledTimes(1)
    expect(mocks.createTarget).toHaveBeenCalledWith(expect.objectContaining({ supplier_id: 10, account_ids: [1] }))
    expect(view.emitted('saved')).toHaveLength(1)
  })
  it('requires an explicit choice when recovery finds multiple matching upstreams', async () => {
    mocks.createSupplier.mockRejectedValueOnce({ message: 'Network error after save' })
    mocks.overview.mockResolvedValue({ suppliers: [supplier, { ...supplier, id: 11 }], monitors: [] })
    const view = render(); await flushPromises(); await choose(view, 1)
    await view.get('form').trigger('submit'); await flushPromises()
    await view.get('form').trigger('submit'); await flushPromises()
    expect(view.text()).toContain('upstreamCenter.import.chooseExisting')
    expect(mocks.createTarget).not.toHaveBeenCalled()
    expect(mocks.createSupplier).toHaveBeenCalledTimes(1)
    await view.get('select').setValue('11')
    await view.get('form').trigger('submit'); await flushPromises()
    expect(mocks.createTarget).toHaveBeenCalledWith(expect.objectContaining({ supplier_id: 11 }))
  })
  it('recovers a group saved despite a lost response and does not post it twice', async () => {
    mocks.createTarget.mockRejectedValueOnce({ message: 'Connection reset' })
    const view = render(); await flushPromises(); await choose(view, 1)
    await view.get('form').trigger('submit'); await flushPromises()
    mocks.overview.mockResolvedValue({ suppliers: [{ ...supplier, targets: [{ id: 30, account_ids: [1] }] }], monitors: [] })
    await view.get('form').trigger('submit'); await flushPromises()
    expect(mocks.createSupplier).toHaveBeenCalledTimes(1)
    expect(mocks.createTarget).toHaveBeenCalledTimes(1)
    expect(view.emitted('saved')).toHaveLength(1)
  })
})
