import { defineComponent } from 'vue'
import { flushPromises, mount, type VueWrapper } from '@vue/test-utils'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import UpstreamTargetDialog from './UpstreamTargetDialog.vue'
import Select from '@/components/common/Select.vue'
import ModelTagInput from '@/components/admin/channel/ModelTagInput.vue'
import type { UpstreamSupplier, UpstreamTarget } from '@/api/admin/upstreamCenter'

const mocks = vi.hoisted(() => ({ create: vi.fn(), update: vi.fn(), models: vi.fn(), accounts: vi.fn(), account: vi.fn() }))
vi.mock('@/api/admin/upstreamCenter', () => ({ upstreamCenterAPI: { createTarget: mocks.create, updateTarget: mocks.update, models: mocks.models } }))
vi.mock('@/api/admin/accounts', () => ({ list: mocks.accounts, getById: mocks.account }))
vi.mock('vue-i18n', () => ({ useI18n: () => ({ t: (key: string) => key }) }))
const dialog = defineComponent({ props: ['show'], template: '<div v-if="show"><slot /><slot name="footer" /></div>' })
const select = defineComponent({ props: ['modelValue', 'options'], emits: ['update:modelValue'], template: '<select class="test-accounts" :value="modelValue" @change="$emit(\'update:modelValue\', $event.target.value)"><option value="">Select</option><option v-for="item in options" :key="item.value" :value="item.value">{{ item.label }}</option></select>' })
const tags = defineComponent({ props: ['models'], emits: ['update:models'], template: '<button class="test-model-add" type="button" @click="$emit(\'update:models\', [\'gpt-test\'])">Add model</button>' })
const supplier = { id: 2, name: 'Supplier', website: 'https://example.com', targets: [] } as unknown as UpstreamSupplier
function target(): UpstreamTarget {
  return { id: 9, supplier_id: 2, name: 'Existing group', provider: 'openai', api_mode: 'responses', endpoint: 'https://example.com', api_key_masked: 'sk-***', models: ['gpt-test'], enabled: true, interval_seconds: 300, timeout_seconds: 45, degraded_threshold_ms: 6000, account_ids: [7], wallet_ref: 'shared', notes: '', statistics: [] } as unknown as UpstreamTarget
}
let wrapper: VueWrapper | undefined
function render(item: UpstreamTarget | null = null, realModelInput = false, parentSupplier: UpstreamSupplier | null = supplier, realSelect = false) {
  wrapper = mount(UpstreamTargetDialog, { attachTo: document.body, props: { show: true, target: item, supplier: parentSupplier }, global: { stubs: { BaseDialog: dialog, Select: realSelect ? false : select, Toggle: true, Icon: true, ModelTagInput: realModelInput ? false : tags, transition: true } } })
  return wrapper
}
async function chooseOption(view: VueWrapper, selector: string, text: string) {
  await view.get(selector).trigger('click')
  await flushPromises()
  const option = [...document.body.querySelectorAll<HTMLElement>('[role="option"]')].find(item => item.textContent?.includes(text))
  expect(option).toBeDefined()
  option!.click()
  await flushPromises()
  expect(view.get(selector).attributes('aria-expanded')).toBe('false')
  expect(document.body.querySelector('[role="listbox"]')).toBeNull()
}
beforeEach(() => { vi.resetAllMocks(); mocks.accounts.mockResolvedValue({ items: [{ id: 7, name: 'Imported account', platform: 'openai' }] }); mocks.account.mockResolvedValue({ id: 7, name: 'Imported account', platform: 'openai', credentials: { base_url: 'https://example.com' } }); mocks.models.mockResolvedValue(['gpt-test']); mocks.create.mockResolvedValue({}); mocks.update.mockResolvedValue({}) })
afterEach(() => { wrapper?.unmount(); wrapper = undefined; document.body.innerHTML = '' })

describe('upstream target credentials and form lifecycle', () => {
  it('imports a standalone monitor from a server-side credential reference without binding business accounts', async () => {
    const view = render(null, true, null)
    await flushPromises()
    expect(view.text()).toContain('upstreamCenter.form.importCredentialHint')
    expect(view.text()).not.toContain('upstreamCenter.form.bindHint')
    await view.get('.test-accounts').setValue('7')
    await view.findAll('button').find(button => button.text() === 'upstreamCenter.form.importAccount')!.trigger('click')
    await flushPromises()
    expect((view.get('#target-key').element as HTMLInputElement).value).toBe('')
    expect(view.get('#target-key').attributes('required')).toBeUndefined()
    expect(view.get('#target-key').attributes('placeholder')).toBe('upstreamCenter.form.importedKeyPlaceholder')
    expect(view.find('#target-wallet').exists()).toBe(false)
    await view.findAll('button').find(button => button.text() === 'upstreamCenter.form.fetchModels')!.trigger('click')
    await flushPromises()
    expect(mocks.models).toHaveBeenCalledWith(expect.objectContaining({ target_id: undefined, account_id: 7, api_key: undefined, endpoint: 'https://example.com' }))
    await view.get('form').trigger('submit')
    await flushPromises()
    expect(mocks.create).toHaveBeenCalledWith(expect.objectContaining({ supplier_id: null, source_account_id: 7, account_ids: [], api_key: undefined, models: ['gpt-5.6-sol'], interval_seconds: 30 }))
  })
  it('replaces credentials through account import when editing a standalone monitor without changing its model or interval', async () => {
    const item = { ...target(), supplier_id: null, account_ids: [] }
    mocks.account.mockResolvedValue({ id: 7, name: 'Imported account', platform: 'anthropic', credentials: {} })
    const view = render(item, true, null)
    await flushPromises()
    await view.get('.test-accounts').setValue('7')
    await view.findAll('button').find(button => button.text() === 'upstreamCenter.form.importAccount')!.trigger('click')
    await flushPromises()
    expect(view.text()).not.toContain('upstreamCenter.form.existingKey')
    await view.findAll('button').find(button => button.text() === 'upstreamCenter.form.fetchModels')!.trigger('click')
    await flushPromises()
    expect(mocks.models).toHaveBeenCalledWith(expect.objectContaining({ target_id: undefined, account_id: 7, provider: 'anthropic', endpoint: 'https://api.anthropic.com' }))
    await view.get('form').trigger('submit')
    await flushPromises()
    expect(mocks.update).toHaveBeenCalledWith(9, expect.objectContaining({ supplier_id: null, source_account_id: 7, account_ids: [], api_key: undefined, provider: 'anthropic', api_mode: 'chat_completions', endpoint: 'https://api.anthropic.com', models: ['gpt-test'], interval_seconds: 300 }))
  })
  it('uses only the most recently imported credential source and clears a manually entered key', async () => {
    mocks.accounts.mockResolvedValue({ items: [{ id: 7, name: 'First account', platform: 'openai' }, { id: 8, name: 'Second account', platform: 'gemini' }] })
    mocks.account.mockResolvedValueOnce({ id: 7, name: 'First account', platform: 'openai', credentials: { base_url: 'https://first.example' } })
      .mockResolvedValueOnce({ id: 8, name: 'Second account', platform: 'gemini', credentials: {} })
    const view = render(null, true, null)
    await flushPromises()
    const importButton = () => view.findAll('button').find(button => button.text() === 'upstreamCenter.form.importAccount')!
    await view.get('.test-accounts').setValue('7')
    await importButton().trigger('click')
    await flushPromises()
    await view.get('#target-key').setValue('manual-key')
    await view.get('.test-accounts').setValue('8')
    await importButton().trigger('click')
    await flushPromises()
    expect((view.get('#target-key').element as HTMLInputElement).value).toBe('')
    await view.get('form').trigger('submit')
    await flushPromises()
    expect(mocks.create).toHaveBeenCalledWith(expect.objectContaining({ source_account_id: 8, account_ids: [], api_key: undefined, endpoint: 'https://generativelanguage.googleapis.com', provider: 'gemini' }))
  })
  it('ignores model discovery from an earlier account after the credential source changes', async () => {
    mocks.accounts.mockResolvedValue({ items: [{ id: 7, name: 'First account', platform: 'openai' }, { id: 8, name: 'Second account', platform: 'openai' }] })
    mocks.account.mockImplementation(async (id: number) => ({ id, name: `Account ${id}`, platform: 'openai', credentials: { base_url: `https://account-${id}.example` } }))
    let resolveOld: (models: string[]) => void = () => undefined
    let resolveCurrent: (models: string[]) => void = () => undefined
    mocks.models.mockReturnValueOnce(new Promise(resolve => { resolveOld = resolve }))
      .mockReturnValueOnce(new Promise(resolve => { resolveCurrent = resolve }))
    const view = render(null, true, null)
    await flushPromises()
    const importButton = () => view.findAll('button').find(button => button.text() === 'upstreamCenter.form.importAccount')!
    const modelButton = () => view.findAll('button').find(button => ['upstreamCenter.form.fetchModels', 'upstreamCenter.form.fetching'].includes(button.text()))!
    await view.get('.test-accounts').setValue('7')
    await importButton().trigger('click')
    await flushPromises()
    await modelButton().trigger('click')
    await view.get('.test-accounts').setValue('8')
    await importButton().trigger('click')
    await flushPromises()
    expect(modelButton().attributes('disabled')).toBeUndefined()
    await modelButton().trigger('click')
    resolveOld(['old-account-model'])
    await flushPromises()
    expect(view.text()).not.toContain('old-account-model')
    expect(modelButton().attributes('disabled')).toBeDefined()
    resolveCurrent(['current-account-model'])
    await flushPromises()
    expect(view.text()).toContain('current-account-model')
    expect(modelButton().attributes('disabled')).toBeUndefined()
  })
  it.each(['endpoint', 'provider', 'key'])('drops the imported credential reference when the %s is manually changed', async field => {
    const view = render(null, true, null, field === 'provider')
    await flushPromises()
    if (field === 'provider') await chooseOption(view, '.select-trigger', 'Imported account')
    else await view.get('.test-accounts').setValue('7')
    await view.findAll('button').find(button => button.text() === 'upstreamCenter.form.importAccount')!.trigger('click')
    await flushPromises()
    if (field === 'endpoint') await view.get('#target-endpoint').setValue('https://manual.example')
    if (field === 'provider') {
      expect(view.findAllComponents(Select).filter(item => !item.props('remote')).every(item => item.props('searchable') === false)).toBe(true)
      expect(view.findAllComponents(Select)[0].props('remote')).toBe(true)
      await chooseOption(view, '#target-provider', 'upstreamCenter.form.providerAnthropic')
      expect(view.find('#target-api-mode').exists()).toBe(false)
      expect(view.getComponent(ModelTagInput).props('platform')).toBe('anthropic')
    }
    if (field === 'key') await view.get('#target-key').setValue('manual-key')
    expect(view.find('button[aria-label="upstreamCenter.remove Imported account"]').exists()).toBe(false)
    if (field !== 'key') {
      await view.get('form').trigger('submit')
      expect(mocks.create).not.toHaveBeenCalled()
      expect(view.get('[role="alert"]').text()).toBe('upstreamCenter.form.requiredKey')
      await view.get('#target-key').setValue('manual-key')
    }
    await view.get('form').trigger('submit')
    await flushPromises()
    expect(mocks.create).toHaveBeenCalledWith(expect.objectContaining({ account_ids: [], source_account_id: undefined, api_key: 'manual-key', provider: field === 'provider' ? 'anthropic' : 'openai' }))
  })
  it('does not retain an imported source after closing and reopening a standalone editor', async () => {
    const item = { ...target(), supplier_id: null, account_ids: [] }
    const view = render(item, true, null)
    await flushPromises()
    await view.get('.test-accounts').setValue('7')
    await view.findAll('button').find(button => button.text() === 'upstreamCenter.form.importAccount')!.trigger('click')
    await flushPromises()
    await view.setProps({ show: false })
    await view.setProps({ show: true })
    await flushPromises()
    expect(view.find('button[aria-label="upstreamCenter.remove Imported account"]').exists()).toBe(false)
    await view.get('form').trigger('submit')
    await flushPromises()
    expect(mocks.update).toHaveBeenCalledWith(9, expect.objectContaining({ account_ids: [], source_account_id: undefined, api_key: undefined, endpoint: item.endpoint, models: item.models }))
  })
  it.each(['remove', 'endpoint', 'provider'])('does not reuse a saved key at the imported address after its source is invalidated by %s', async change => {
    const item = { ...target(), supplier_id: null, account_ids: [] }
    mocks.account.mockResolvedValue({ id: 7, name: 'Imported account', platform: 'openai', credentials: { base_url: 'https://another-upstream.example' } })
    const view = render(item, true, null)
    await flushPromises()
    await view.get('.test-accounts').setValue('7')
    await view.findAll('button').find(button => button.text() === 'upstreamCenter.form.importAccount')!.trigger('click')
    await flushPromises()
    if (change === 'remove') await view.get('button[aria-label="upstreamCenter.remove Imported account"]').trigger('click')
    if (change === 'endpoint') await view.get('#target-endpoint').setValue('https://manually-edited.example')
    if (change === 'provider') await view.get('#target-provider').setValue('anthropic')
    expect(view.get('#target-key').attributes('required')).toBeDefined()
    expect(view.get('#target-key').attributes('placeholder')).toBe('upstreamCenter.form.apiKeyPlaceholder')
    expect(view.text()).toContain('upstreamCenter.form.changedConnectionKeyHint')
    expect(view.findAll('button').find(button => button.text() === 'upstreamCenter.form.fetchModels')!.attributes('disabled')).toBeDefined()
    await view.get('form').trigger('submit')
    expect(mocks.update).not.toHaveBeenCalled()
    expect(view.get('[role="alert"]').text()).toBe('upstreamCenter.form.requiredKey')
    await view.get('#target-key').setValue('new-manual-key')
    await view.get('form').trigger('submit')
    await flushPromises()
    expect(mocks.update).toHaveBeenCalledWith(9, expect.objectContaining({ source_account_id: undefined, account_ids: [], api_key: 'new-manual-key' }))
  })
  it.each([['upstream group', supplier], ['standalone monitor', null]] as const)('creates a new %s with the shared model and 30 second defaults', async (_name, parentSupplier) => {
    const view = render(null, true, parentSupplier)
    await flushPromises()
    expect(view.getComponent(ModelTagInput).props('models')).toEqual(['gpt-5.6-sol'])
    expect((view.get('#target-interval').element as HTMLInputElement).value).toBe('30')
    expect(view.get('#target-interval').attributes('min')).toBe('30')
    await view.get('#target-name').setValue('New monitor')
    await view.get('#target-endpoint').setValue('https://upstream.example')
    await view.get('#target-key').setValue('test-key')
    await view.get('form').trigger('submit')
    await flushPromises()
    expect(mocks.create).toHaveBeenCalledWith(expect.objectContaining({ models: ['gpt-5.6-sol'], interval_seconds: 30, supplier_id: parentSupplier?.id ?? null }))
  })
  it('keeps customized monitoring settings when importing an account with a different model whitelist', async () => {
    mocks.account.mockResolvedValue({ id: 7, name: 'Imported account', platform: 'anthropic', credentials: { base_url: 'https://example.com', model_mapping: { 'account-only-model': 'remote-model' } } })
    const view = render(null, true)
    await flushPromises()
    view.getComponent(ModelTagInput).vm.$emit('update:models', ['my-custom-model'])
    await view.get('#target-interval').setValue('90')
    await view.get('.test-accounts').setValue('7')
    await view.findAll('button').find(button => button.text() === 'upstreamCenter.form.importAccount')!.trigger('click')
    await flushPromises()
    expect(view.getComponent(ModelTagInput).props('models')).toEqual(['my-custom-model'])
    await view.get('form').trigger('submit')
    await flushPromises()
    expect(mocks.create).toHaveBeenCalledWith(expect.objectContaining({ provider: 'anthropic', models: ['my-custom-model'], interval_seconds: 90, account_ids: [7] }))
  })
  it('preserves both saved models when only the name is edited and the API key is left blank', async () => {
    const item = { ...target(), models: ['gpt-4o-mini', 'gpt-4o'] }
    const view = render(item, true)
    await flushPromises()
    const modelInput = view.getComponent(ModelTagInput)
    expect(modelInput.props('models')).toEqual(['gpt-4o-mini', 'gpt-4o'])
    expect(modelInput.findAll('span').map(tag => tag.text())).toEqual(['gpt-4o-mini', 'gpt-4o'])
    await view.get('#target-name').setValue('Renamed monitor')
    await view.get('#target-name').trigger('keydown', { key: 'Backspace' })
    await view.get('#target-name').trigger('blur')
    await modelInput.get('input').trigger('blur')
    expect((view.get('#target-key').element as HTMLInputElement).value).toBe('')
    await view.get('form').trigger('submit')
    await flushPromises()
    expect(mocks.update).toHaveBeenCalledWith(9, expect.objectContaining({ name: 'Renamed monitor', api_key: undefined, models: ['gpt-4o-mini', 'gpt-4o'], interval_seconds: 300 }))
    expect(item.models).toEqual(['gpt-4o-mini', 'gpt-4o'])
    expect(view.emitted('saved')).toHaveLength(1)
  })
  it('hydrates saved selection and collapses the protocol picker while retaining a blank-key update', async () => {
    const view = render(target(), false, supplier, true)
    await flushPromises()
    expect((view.get('#target-name').element as HTMLInputElement).value).toBe('Existing group')
    expect((view.get('#target-key').element as HTMLInputElement).value).toBe('')
    expect(view.find('select').exists()).toBe(false)
    expect(view.get('#target-api-mode').text()).toContain('Responses')
    await view.get('#target-api-mode').trigger('click')
    await flushPromises()
    expect(document.body.querySelector('.select-search-input')).toBeNull()
    await view.get('#target-api-mode').trigger('click')
    await chooseOption(view, '#target-api-mode', 'Chat Completions')
    expect(view.get('#target-api-mode').text()).toContain('Chat Completions')
    await view.get('form').trigger('submit')
    await flushPromises()
    expect(mocks.update).toHaveBeenCalledWith(9, expect.objectContaining({ api_key: undefined, account_ids: [7], models: ['gpt-test'], api_mode: 'chat_completions' }))
    expect(view.emitted('saved')).toHaveLength(1)
    expect(view.emitted('close')).toHaveLength(1)
  })
  it('imports and discovers models using the server-side account reference without changing the source account', async () => {
    const view = render()
    await flushPromises()
    await view.get('.test-accounts').setValue('7')
    const importButton = view.findAll('button').find(button => button.text() === 'upstreamCenter.form.importAccount')!
    await importButton.trigger('click'); await flushPromises()
    const modelButton = view.findAll('button').find(button => button.text() === 'upstreamCenter.form.fetchModels')!
    await modelButton.trigger('click'); await flushPromises()
    expect(mocks.models).toHaveBeenCalledWith(expect.objectContaining({ account_id: 7, api_key: undefined, endpoint: 'https://example.com' }))
    expect(view.getComponent(tags).props('models')).toEqual(['gpt-5.6-sol'])
    await view.get('.test-model-add').trigger('click')
    await view.get('form').trigger('submit'); await flushPromises()
    expect(mocks.create).toHaveBeenCalledWith(expect.objectContaining({ name: 'Imported account', account_ids: [7], api_key: undefined, models: ['gpt-test'], interval_seconds: 30 }))
  })
  it('keeps validation errors in the open form without making a request', async () => {
    const view = render()
    view.getComponent(tags).vm.$emit('update:models', [])
    await view.get('form').trigger('submit')
    expect(view.get('[role="alert"]').text()).toBe('upstreamCenter.form.requiredModels')
    expect(mocks.create).not.toHaveBeenCalled()
    expect(view.emitted('close')).toBeUndefined()
  })
  it('does not let an account import from a closed dialog lock or overwrite the reopened form', async () => {
    let rejectOldImport: (error: unknown) => void = () => undefined
    let resolveNewImport: (account: unknown) => void = () => undefined
    mocks.account.mockReturnValueOnce(new Promise((_, reject) => { rejectOldImport = reject }))
      .mockReturnValueOnce(new Promise(resolve => { resolveNewImport = resolve }))
    const view = render()
    await flushPromises()
    const importButton = () => view.findAll('button').find(button => button.text() === 'upstreamCenter.form.importAccount')!
    await view.get('.test-accounts').setValue('7')
    await importButton().trigger('click')
    await view.setProps({ show: false })
    await view.setProps({ show: true })
    await flushPromises()
    await view.get('.test-accounts').setValue('7')
    expect(importButton().attributes('disabled')).toBeUndefined()
    await importButton().trigger('click')
    expect(mocks.account).toHaveBeenCalledTimes(2)

    rejectOldImport({ message: 'Old account request failed' })
    await flushPromises()
    expect(view.text()).not.toContain('Old account request failed')
    expect(importButton().attributes('disabled')).toBeDefined()

    resolveNewImport({ id: 7, name: 'Current account', platform: 'openai', credentials: { base_url: 'https://current.example' } })
    await flushPromises()
    expect((view.get('#target-name').element as HTMLInputElement).value).toBe('Current account')
    expect((view.get('#target-endpoint').element as HTMLInputElement).value).toBe('https://current.example')
  })
  it('lets a reopened editor discover models without an older request clearing its loading state', async () => {
    let resolveOldModels: (models: string[]) => void = () => undefined
    let resolveNewModels: (models: string[]) => void = () => undefined
    mocks.models.mockReturnValueOnce(new Promise(resolve => { resolveOldModels = resolve }))
      .mockReturnValueOnce(new Promise(resolve => { resolveNewModels = resolve }))
    const view = render(target())
    await flushPromises()
    const modelButton = () => view.findAll('button').find(button => ['upstreamCenter.form.fetchModels', 'upstreamCenter.form.fetching'].includes(button.text()))!
    await modelButton().trigger('click')
    await view.setProps({ show: false })
    await view.setProps({ show: true })
    await flushPromises()
    expect(modelButton().attributes('disabled')).toBeUndefined()
    await modelButton().trigger('click')
    expect(mocks.models).toHaveBeenCalledTimes(2)

    resolveOldModels(['old-model'])
    await flushPromises()
    expect(view.text()).not.toContain('old-model')
    expect(modelButton().attributes('disabled')).toBeDefined()
    resolveNewModels(['current-model'])
    await flushPromises()
    expect(view.text()).toContain('current-model')
    expect(modelButton().attributes('disabled')).toBeUndefined()
  })
  it('prevents duplicate submissions and keeps server errors reviewable', async () => {
    let rejectSave: (error: unknown) => void = () => undefined
    mocks.update.mockReturnValue(new Promise((_, reject) => { rejectSave = reject }))
    const view = render(target())
    await view.get('form').trigger('submit')
    await view.get('form').trigger('submit')
    expect(mocks.update).toHaveBeenCalledTimes(1)
    rejectSave({ message: 'A check is still running; try again shortly.' })
    await flushPromises()
    expect(view.get('[role="alert"]').text()).toContain('A check is still running')
    expect(view.emitted('saved')).toBeUndefined()
    expect(view.emitted('close')).toBeUndefined()
  })
})
